// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1k8Jv4_-H3wzOmvkHRfFvmDjMqMQ8U0Q',
    appId: '1:1005926939220:web:0c8da201e1ae0d6c688bc1',
    messagingSenderId: '1005926939220',
    projectId: 'stepout-1',
    authDomain: 'stepout-1.firebaseapp.com',
    storageBucket: 'stepout-1.firebasestorage.app',
    measurementId: 'G-M36PD5JS15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkoK7p1xEIzmDDRJc4hYdtLzFYA0RzCqc',
    appId: '1:1005926939220:android:5ab00d16c448ffeb688bc1',
    messagingSenderId: '1005926939220',
    projectId: 'stepout-1',
    storageBucket: 'stepout-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pAnySnief9vh2KAxaC_J4fnFmHPAzWc',
    appId: '1:1005926939220:ios:93a86af3fdf345b7688bc1',
    messagingSenderId: '1005926939220',
    projectId: 'stepout-1',
    storageBucket: 'stepout-1.firebasestorage.app',
    iosClientId: '1005926939220-q7r86ef8cf2ak5qs67gmrt3boitv5t2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepOut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9pAnySnief9vh2KAxaC_J4fnFmHPAzWc',
    appId: '1:1005926939220:ios:93a86af3fdf345b7688bc1',
    messagingSenderId: '1005926939220',
    projectId: 'stepout-1',
    storageBucket: 'stepout-1.firebasestorage.app',
    iosClientId: '1005926939220-q7r86ef8cf2ak5qs67gmrt3boitv5t2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stepOut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1k8Jv4_-H3wzOmvkHRfFvmDjMqMQ8U0Q',
    appId: '1:1005926939220:web:ddd79e91c1d696be688bc1',
    messagingSenderId: '1005926939220',
    projectId: 'stepout-1',
    authDomain: 'stepout-1.firebaseapp.com',
    storageBucket: 'stepout-1.firebasestorage.app',
    measurementId: 'G-4SKLMGEMFL',
  );
}
